### ISSUE TITLE
细想可能产生的文件内容会比smallwidth的基础方案更加的大

### ISSUE THREAD

**Issue by ymqq** [xiaolutang/easySmallWidth#2]
细想可能产生的文件内容会比smallwidth的基础方案更加的大；

因为，在一个成熟的项目中，每个页面元素众多，每个元素基本上都会有自己的尺寸dimen，这个要是生成的话，数量会超出预期。

也就会导致产生的适配dimen文件大小会随着项目的不断变化，不断增加。

而基础方案的dimen适配的文件大小是可以预估的。

**Comment by xiaolutang** [comment]
下一个版本发布的时候解决这个问题

**Comment by xiaolutang** [comment]
要解决这个问题，首先要知道为什么基础smallWidth文件不会 变大，因为基础的smallWidth会提前准备好所需要的的dimens文件，然后通过引用（@dimen/）的方式来使用它们。如果使用easySmallWidth您同样 可以采用这个逻辑。提前准备好对应的dimens文件，开启适配。等待对应的sw文件生成之后，关闭掉这个插件。这样esaySmallwidth就不会在生成对应的文件。
还有，我们在开发的时候可以对一些常规的dimen直接进行复用，而不是为 每一个 元素都生成自己的dimen尺寸
